name: asset_generators
dependencies:
  args: any
  path: "^1.4.2"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  assets:
    - dart-ui/blend_mode_destination.jpeg
    - dart-ui/blend_mode_source.png
  uses-material-design: true
